Revert e6ed9fdc8d9c
The commit moved some activities to a honey_geography directory but that
directory doesn't exist on pootle anymore so when the add_langs script is
run it throws this error;

Traceback (most recent call last):
  File "/var/lib/pootle/maintenance/helpers/admin/add_langs.py", line 36, in <module>
    for project_lang in os.listdir(project_langs_dir):
OSError: [Errno 2] No such file or directory: '/var/lib/pootle/translations/honey_geography'

This commit reverts that and the script now runs as expected.

Signed-off-by: Ibiam Chihurumnaya <ibiamchihurumnaya@gmail.com>